site_name: Tvtrung's Blog
site_url: https://tvtrungg.github.io/MkDocs

theme:
  name: material
  language: en
  palette:
    primary: teal
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy # Thêm nút sao chép code
    - content.tabs # Thêm tabs
    - search.suggest # Thêm gợi ý tìm kiếm
    - search.full # Thêm tìm kiếm toàn văn
  favicon: img/logo.png
  logo: img/logo.png

plugins:
  - minify # Tối ưu hóa tài nguyên
  - awesome-pages # Tạo trang tự động
  - search
  - i18n:
      default_language: en
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: vi
          name: Tiếng Việt
          build: true
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
copyright: Copyright &copy; 2024 Vinh Trung THIEU
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tvtrungg
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tvtrungg
      name: LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://tvtrung.vercel.app/
      name: Website
